package de.zalando.zomcat.flowid;

/**
 * payload information encoded in a Flow-ID generated by FlowId.generateFlowIdWithPayload().
 *
 * @author  hjacobs
 */
public class FlowIdPayload {

    // session ID prefix: first 5 bytes of session ID in hex format (complete session ID is 16 Bytes, i.e. UUID)
    private String sessionPrefix;

    // remote IP address in dotted decimal format, e.g. 127.0.0.1
    private String remoteAddress;

    // frontend user ID or customer number suffix
    private Integer userId;

    public FlowIdPayload(final String sessionPrefix, final String remoteAddress, final Integer userId) {
        this.sessionPrefix = sessionPrefix;
        this.remoteAddress = remoteAddress;
        this.userId = userId;
    }

    public String getRemoteAddress() {
        return remoteAddress;
    }

    public void setRemoteAddress(final String remoteAddress) {
        this.remoteAddress = remoteAddress;
    }

    public String getSessionPrefix() {
        return sessionPrefix;
    }

    public void setSessionPrefix(final String sessionPrefix) {
        this.sessionPrefix = sessionPrefix;
    }

    public Integer getUserId() {
        return userId;
    }

    public void setUserId(final Integer userId) {
        this.userId = userId;
    }

}
