CREATE TYPE zz_commons.app_domain AS (
  id                                     smallint,
  code                                   varchar(255),
  name                                   varchar(255),
  app_url                                varchar(255),
  static_url                             varchar(255),
  currency                               char(3),
  locale                                 varchar(8),
  shipping_countries                     char(2)[],
  stocks                                 smallint[],
  root_category_id                       integer,
  payment_methods                        varchar(50)[],
  docdata_affiliate_id                   varchar(2),
  last_modified                          timestamp without time zone,
  priority                               smallint,
  appdomain_set_id                       smallint,
  default_newsletter_id                  smallint,
  customer_appdomain_set_id              smallint,
  is_short_sale                          boolean,
  is_lounge                              boolean,
  principal_code                         varchar(20),
  customer_principal_code                varchar(20),
  mobile_url                             varchar(255),
  is_statistical_article_number_required boolean
);
