CREATE TABLE zz_commons.partner (
    p_id integer NOT NULL,
    p_name text NOT NULL,
    p_shipping_countries varchar[] NOT NULL,
    p_appdomain_ids smallint[],
    p_last_modified timestamp without time zone NOT NULL DEFAULT clock_timestamp(),
    p_remote_server_name text NOT NULL,
    p_stock_id smallint NULL,
    p_type INTEGER NOT NULL, -- type from partner service table
    p_is_price_calculation_enabled boolean NOT NULL DEFAULT FALSE,
    p_ranking integer NOT NULL DEFAULT 100,
    p_creditor_number text,
    p_tax_key varchar(8) NOT NULL DEFAULT 'A1',
    p_tax_rate integer NOT NULL DEFAULT 1900,
    p_parcel_services zz_commons.parcel_service[] NOT NULL,
    p_parcel_service_types zz_commons.parcel_service_type[] NOT NULL,
    p_legal_form text NOT NULL,
    PRIMARY KEY (p_id )
);

ALTER TABLE zz_commons.partner OWNER TO zalando;

COMMENT ON TABLE zz_commons.partner IS 'a partner is using the zalando platform to offer and sell his own articles. the shipping is handled by the partner';
COMMENT ON COLUMN zz_commons.partner.p_stock_id IS 'a reference to the stock of the partner';
COMMENT ON COLUMN zz_commons.partner.p_name IS 'the name of the partner';
COMMENT ON COLUMN zz_commons.partner.p_shipping_countries IS 'countries this partner delivers to';
COMMENT ON COLUMN zz_commons.partner.p_remote_server_name IS 'name of the shard where entities for the partner is persisted';
COMMENT ON COLUMN zz_commons.partner.p_is_price_calculation_enabled IS 'price calculation for that partner is enabled';
COMMENT ON COLUMN zz_commons.partner.p_ranking IS 'Price calculation ranking. A lower rank means this partner will be preferred over others.';
COMMENT ON COLUMN zz_commons.partner.p_creditor_number IS 'Zalando SAP Creditor Number';
COMMENT ON COLUMN zz_commons.partner.p_tax_key IS 'Key used to determine Value Added Tax handling for Partner';
COMMENT ON COLUMN zz_commons.partner.p_tax_rate IS 'Value used to determine Value Added Tax handling for Partner';
COMMENT ON COLUMN zz_commons.partner.p_parcel_services IS 'Parcel Services supported by Partner';
COMMENT ON COLUMN zz_commons.partner.p_parcel_service_types IS 'Parcel Service selection type for Shop Frontend';
COMMENT ON COLUMN zz_commons.partner.p_legal_form IS 'Company name of Partner Company - may differ from Partner Name';


------------------------------------------------------------------------------------------------------------------------
--
-- Default Data for Table
--
-- PLEASE KEEP THE ORDER ACCORDING TO PARTNER_ID, do NOT append new partners but place them in
--    the correct order according to the new partner(s) partner id(s).
--
------------------------------------------------------------------------------------------------------------------------

INSERT INTO zz_commons.partner (p_id,p_appdomain_ids, p_stock_id, p_name, p_legal_form, p_shipping_countries, p_remote_server_name, p_type, p_is_price_calculation_enabled, p_ranking, p_creditor_number, p_tax_key, p_tax_rate, p_parcel_services, p_parcel_service_types)
VALUES
(3001, ARRAY[1]::smallint[],       3001::smallint, 'Outfitter',                 'OUTFITTER FIVE GmbH',                     ARRAY['DE'], 'dblink_partner1_queue', 3001, TRUE,  100, '23000003', 'A1', 1900, '{DHL}'::zz_commons.parcel_service[], '{EQUIVALENT}'::zz_commons.parcel_service_type[]),
(3002, ARRAY[1]::smallint[],       3002::smallint, 'Sobeos',                    'Sobeos GmbH',                             ARRAY['DE'], 'dblink_partner2_queue', 3002, TRUE,  100, '23000005', 'A1', 1900, '{DHL}'::zz_commons.parcel_service[], '{EQUIVALENT}'::zz_commons.parcel_service_type[]),
(3003, ARRAY[1]::smallint[],       3003::smallint, 'schuhplus',                 'schuhplus GmbH',                          ARRAY['DE'], 'dblink_partner1_queue', 3003, TRUE,  100, '23000001', 'A1', 1900, '{DHL}'::zz_commons.parcel_service[], '{EQUIVALENT}'::zz_commons.parcel_service_type[]),
(3004, ARRAY[1]::smallint[],       3004::smallint, 'OBOY',                      'OBOY Retail GmbH',                        ARRAY['DE'], 'dblink_partner2_queue', 3004, TRUE,  100, '23000007', 'A1', 1900, '{DHL}'::zz_commons.parcel_service[], '{EQUIVALENT}'::zz_commons.parcel_service_type[]),
(3005, ARRAY[1]::smallint[],       3005::smallint, 'Coutie',                    'Coutie GmbH',                             ARRAY['DE'], 'dblink_partner1_queue', 3005, TRUE,  100, '23000002', 'A1', 1900, '{DHL}'::zz_commons.parcel_service[], '{EQUIVALENT}'::zz_commons.parcel_service_type[]),
(3006, ARRAY[1]::smallint[],       3006::smallint, 'Giesswein',                 'Giesswein AG',                            ARRAY['DE'], 'dblink_partner2_queue', 3006, TRUE,  100, '23000000', 'A5', 2000, '{DHL}'::zz_commons.parcel_service[], '{EQUIVALENT}'::zz_commons.parcel_service_type[]),
(3007, ARRAY[1]::smallint[],       3007::smallint, 'FourFlavor',                'FourFlavor UG',                           ARRAY['DE'], 'dblink_partner1_queue', 3007, TRUE,  100, '23000004', 'A1', 1900, '{DHL}'::zz_commons.parcel_service[], '{EQUIVALENT}'::zz_commons.parcel_service_type[]),
(3008, ARRAY[1]::smallint[],       3008::smallint, 'surf4shoes',                'surf4shoes GmbH',                         ARRAY['DE'], 'dblink_partner2_queue', 3008, TRUE,  100, '23000006', 'A1', 1900, '{DHL}'::zz_commons.parcel_service[], '{EQUIVALENT}'::zz_commons.parcel_service_type[]),
(3009, ARRAY[1]::smallint[],       3009::smallint, 'ERIMA',                     'OUTFITTER FIVE GmbH',                     ARRAY['DE'], 'dblink_partner1_queue', 3009, TRUE,  100, '23000003', 'A1', 1900, '{DHL}'::zz_commons.parcel_service[], '{EQUIVALENT}'::zz_commons.parcel_service_type[]),
(3010, ARRAY[1]::smallint[],       3010::smallint, 'Jako',                      'OUTFITTER FIVE GmbH',                     ARRAY['DE'], 'dblink_partner2_queue', 3010, TRUE,  100, '23000003', 'A1', 1900, '{DHL}'::zz_commons.parcel_service[], '{EQUIVALENT}'::zz_commons.parcel_service_type[]),
(3011, ARRAY[1]::smallint[],       3011::smallint, 'CBR',                       'CBR eCommerce GmbH',                      ARRAY['DE'], 'dblink_partner1_queue', 3011, TRUE,  100, '23000011', 'A1', 1900, '{DHL}'::zz_commons.parcel_service[], '{EQUIVALENT}'::zz_commons.parcel_service_type[]),
(3012, ARRAY[1]::smallint[],       3012::smallint, 'SC24',                      'SC24.com AG',                             ARRAY['DE'], 'dblink_partner2_queue', 3012, TRUE,  100, '23000010', 'A1', 1900, '{DHL}'::zz_commons.parcel_service[], '{EQUIVALENT}'::zz_commons.parcel_service_type[]),
(3013, ARRAY[1]::smallint[],       3013::smallint, 'WarehouseOne',              'Warehouse One',                           ARRAY['DE'], 'dblink_partner1_queue', 3013, FALSE, 100, '23000023', 'A1', 1900, '{DHL}'::zz_commons.parcel_service[], '{EQUIVALENT}'::zz_commons.parcel_service_type[]),
(3014, ARRAY[1]::smallint[],       3014::smallint, 'ArmedAngels',               'Social Fashion Company GmbH',             ARRAY['DE'], 'dblink_partner2_queue', 3014, TRUE,  100, '23000012', 'A1', 1900, '{DHL}'::zz_commons.parcel_service[], '{EQUIVALENT}'::zz_commons.parcel_service_type[]),
(3015, ARRAY[1]::smallint[],       3015::smallint, 'Shopping4Labels',           'Capidema GmbH',                           ARRAY['DE'], 'dblink_partner1_queue', 3015, FALSE, 100, '23000013', 'A1', 1900, '{DHL}'::zz_commons.parcel_service[], '{EQUIVALENT}'::zz_commons.parcel_service_type[]),
(3016, ARRAY[1]::smallint[],       3016::smallint, 'DerMarkenJuwelier',         'DerMarkenJuwelier GmbH & Co. KG',         ARRAY['DE'], 'dblink_partner2_queue', 3016, FALSE, 100, '23000014', 'A1', 1900, '{DHL}'::zz_commons.parcel_service[], '{EQUIVALENT}'::zz_commons.parcel_service_type[]),
(3017, ARRAY[1]::smallint[],       3017::smallint, 'Facett',                    'Facett GmbH (Mentor Brands/Luxxos.com)',  ARRAY['DE'], 'dblink_partner1_queue', 3017, FALSE, 100, '23000015', 'A1', 1900, '{DHL}'::zz_commons.parcel_service[], '{EQUIVALENT}'::zz_commons.parcel_service_type[]),
(3018, ARRAY[1]::smallint[],       3018::smallint, 'fan_and_more',              'fan & more by Casalino',                  ARRAY['DE'], 'dblink_partner2_queue', 3018, TRUE,  100, '23000016', 'A1', 1900, '{DHL}'::zz_commons.parcel_service[], '{EQUIVALENT}'::zz_commons.parcel_service_type[]),
(3019, ARRAY[1]::smallint[],       3019::smallint, 'Ginger_and_Grace',          '<UNKNOWN>',                               ARRAY['DE'], 'dblink_partner1_queue', 3019, FALSE, 100, '23000017', 'A1', 1900, '{DHL}'::zz_commons.parcel_service[], '{EQUIVALENT}'::zz_commons.parcel_service_type[]),
(3020, ARRAY[1]::smallint[],       3020::smallint, 'G-LAGO',                    'Motion Fashion Network Europe GmbH',      ARRAY['DE'], 'dblink_partner2_queue', 3020, TRUE,  100, '23000018', 'A1', 1900, '{DHL}'::zz_commons.parcel_service[], '{EQUIVALENT}'::zz_commons.parcel_service_type[]),
(3021, ARRAY[1]::smallint[],       3021::smallint, 'GREENALITY',                'GREENALITY',                              ARRAY['DE'], 'dblink_partner1_queue', 3021, TRUE,  100, '23000019', 'A1', 1900, '{DHL}'::zz_commons.parcel_service[], '{EQUIVALENT}'::zz_commons.parcel_service_type[]),
(3022, ARRAY[1]::smallint[],       3022::smallint, 'Koffer-Arena',              '(tasko Products GmbH',                    ARRAY['DE'], 'dblink_partner2_queue', 3022, TRUE,  100, '23000020', 'A1', 1900, '{DHL}'::zz_commons.parcel_service[], '{EQUIVALENT}'::zz_commons.parcel_service_type[]),
(3023, ARRAY[1]::smallint[],       3023::smallint, 'koffer-direkt',             'koffer-direkt.de GmbH & Co. KG',          ARRAY['DE'], 'dblink_partner1_queue', 3023, TRUE,  100, '23000021', 'A1', 1900, '{DHL}'::zz_commons.parcel_service[], '{EQUIVALENT}'::zz_commons.parcel_service_type[]),
(3024, ARRAY[1]::smallint[],       3024::smallint, 'liaison_dangereuse',        'SD Fashion GmbH & Co. KG',                ARRAY['DE'], 'dblink_partner2_queue', 3024, FALSE, 100, '23000022', 'A1', 1900, '{DHL}'::zz_commons.parcel_service[], '{EQUIVALENT}'::zz_commons.parcel_service_type[]),
(3025, ARRAY[1]::smallint[],       3025::smallint, 'Shinatic',                  'AHE GmbH & Co. KG',                       ARRAY['DE'], 'dblink_partner1_queue', 3025, FALSE, 100, '23000025', 'A1', 1900, '{DHL}'::zz_commons.parcel_service[], '{EQUIVALENT}'::zz_commons.parcel_service_type[]),
(3026, ARRAY[1]::smallint[],       3026::smallint, 'Hut',                       'Anthec GmbH',                             ARRAY['DE'], 'dblink_partner2_queue', 3026, FALSE, 100, '23000025', 'A1', 1900, '{DHL}'::zz_commons.parcel_service[], '{EQUIVALENT}'::zz_commons.parcel_service_type[]),
(3027, ARRAY[1]::smallint[],       3027::smallint, 'Eterna',                    'Eterna Mode GmbH',                        ARRAY['DE'], 'dblink_partner1_queue', 3027, TRUE,  100, '23000026', 'A1', 1900, '{DHL}'::zz_commons.parcel_service[], '{EQUIVALENT}'::zz_commons.parcel_service_type[]),
(3028, ARRAY[1]::smallint[],       3028::smallint, 'idress',                    'Idress bv',                               ARRAY['DE'], 'dblink_partner2_queue', 3028, TRUE,  100, '23000039', 'A1', 1900, '{DHL}'::zz_commons.parcel_service[], '{EQUIVALENT}'::zz_commons.parcel_service_type[]),
(3029, ARRAY[1]::smallint[],       3029::smallint, 'Cecil CBR',                 'CBR eCommerce GmbH',                      ARRAY['DE'], 'dblink_partner1_queue', 3029, TRUE,  100, '23000011', 'A1', 1900, '{DHL}'::zz_commons.parcel_service[], '{EQUIVALENT}'::zz_commons.parcel_service_type[]),
(3030, ARRAY[1]::smallint[],       3030::smallint, 'One Touch',                 'CBR eCommerce GmbH',                      ARRAY['DE'], 'dblink_partner2_queue', 3030, TRUE,  100, '23000011', 'A1', 1900, '{DHL}'::zz_commons.parcel_service[], '{EQUIVALENT}'::zz_commons.parcel_service_type[]),
(3031, ARRAY[1]::smallint[],       3031::smallint, 'Kraxel',                    'kraxel.com Handels GmbH',                 ARRAY['DE'], 'dblink_partner2_queue', 3031, TRUE,  100, '23000046', 'A1', 1900, '{DHL}'::zz_commons.parcel_service[], '{EQUIVALENT}'::zz_commons.parcel_service_type[]),
(3032, ARRAY[1]::smallint[],       3032::smallint, 'Taschenkaufhaus',           'Taschenkaufhaus gmbh',                    ARRAY['DE'], 'dblink_partner2_queue', 3032, TRUE,  100, '23000030', 'A1', 1900, '{DHL}'::zz_commons.parcel_service[], '{EQUIVALENT}'::zz_commons.parcel_service_type[]),
(3033, ARRAY[1]::smallint[],       3033::smallint, 'März',                      'März München GmbH',                       ARRAY['DE'], 'dblink_partner1_queue', 3033, TRUE,  100, '23000031', 'A1', 1900, '{DHL}'::zz_commons.parcel_service[], '{EQUIVALENT}'::zz_commons.parcel_service_type[]),
(3034, ARRAY[1]::smallint[],       3034::smallint, 'Handtuchwelt',              'comwave GmbH',                            ARRAY['DE'], 'dblink_partner2_queue', 3034, FALSE, 100, '23000032', 'A1', 1900, '{DHL}'::zz_commons.parcel_service[], '{EQUIVALENT}'::zz_commons.parcel_service_type[]),
(3035, ARRAY[1]::smallint[],       3035::smallint, 'Center Court',              'Sportartikelvertrieb ohg',                ARRAY['DE'], 'dblink_partner1_queue', 3035, FALSE, 100, '23000033', 'A1', 1900, '{DHL}'::zz_commons.parcel_service[], '{EQUIVALENT}'::zz_commons.parcel_service_type[]),
(3036, ARRAY[1]::smallint[],       3036::smallint, 'Apparel Partner',           'Apparel Partners Int. GmbH',              ARRAY['DE'], 'dblink_partner2_queue', 3036, FALSE, 100, '23000034', 'A1', 1900, '{DHL}'::zz_commons.parcel_service[], '{EQUIVALENT}'::zz_commons.parcel_service_type[]),
(3037, ARRAY[1]::smallint[],       3037::smallint, 'Fashion Art',               'Fashionart ltd',                          ARRAY['DE'], 'dblink_partner1_queue', 3037, FALSE, 100, '23000035', 'A1', 1900, '{DHL}'::zz_commons.parcel_service[], '{EQUIVALENT}'::zz_commons.parcel_service_type[]),
(3038, ARRAY[1]::smallint[],       3038::smallint, 'Horst Kleckow',             'Horst Kleckow GmbH',                      ARRAY['DE'], 'dblink_partner2_queue', 3038, FALSE, 100, '23000036', 'A1', 1900, '{DHL}'::zz_commons.parcel_service[], '{EQUIVALENT}'::zz_commons.parcel_service_type[]),
(3039, ARRAY[1]::smallint[],       3039::smallint, '24colours',                 '24colors gmbh',                           ARRAY['DE'], 'dblink_partner1_queue', 3039, FALSE, 100, '23000037', 'A1', 1900, '{DHL}'::zz_commons.parcel_service[], '{EQUIVALENT}'::zz_commons.parcel_service_type[]),
(3040, ARRAY[1]::smallint[],       3040::smallint, 'Figueroa',                  'Figueroa',                                ARRAY['DE'], 'dblink_partner2_queue', 3040, FALSE, 100, '23000038', 'A1', 1900, '{DHL}'::zz_commons.parcel_service[], '{EQUIVALENT}'::zz_commons.parcel_service_type[]),
(3041, ARRAY[1]::smallint[],       3041::smallint, 'Carl Gross',                'Gross Retail',                            ARRAY['DE'], 'dblink_partner1_queue', 3041, TRUE,  100, '23000040', 'A1', 1900, '{DHL}'::zz_commons.parcel_service[], '{EQUIVALENT}'::zz_commons.parcel_service_type[]),
(3042, ARRAY[1]::smallint[],       3042::smallint, 'Mey',                       'Mey Handels GmbH',                        ARRAY['DE'], 'dblink_partner2_queue', 3042, TRUE,  100, '23000041', 'A1', 1900, '{DHL}'::zz_commons.parcel_service[], '{EQUIVALENT}'::zz_commons.parcel_service_type[]),
(3043, ARRAY[1]::smallint[],       3043::smallint, 'Noppies Deutschland',       'Noppies deutschland',                     ARRAY['DE'], 'dblink_partner1_queue', 3043, TRUE,  100, '23000042', 'A8', 1900, '{DHL}'::zz_commons.parcel_service[], '{EQUIVALENT}'::zz_commons.parcel_service_type[]),
(3044, ARRAY[1]::smallint[],       3044::smallint, 'schuhe-im-netz',            'Lemax shoe-fashion GmbH',                 ARRAY['DE'], 'dblink_partner2_queue', 3044, FALSE, 100, '23000045', 'A1', 1900, '{DHL}'::zz_commons.parcel_service[], '{EQUIVALENT}'::zz_commons.parcel_service_type[]),
(3045, ARRAY[1]::smallint[],       3045::smallint, 'design3000',                'design3000 GmbH',                         ARRAY['DE'], 'dblink_partner1_queue', 3045, FALSE, 100, '23000047', 'A1', 1900, '{DHL}'::zz_commons.parcel_service[], '{EQUIVALENT}'::zz_commons.parcel_service_type[]),
(3046, ARRAY[1]::smallint[],       3046::smallint, 'Apriori'   ,                'APRIORI Textilvertriebs GmbH',            ARRAY['DE'], 'dblink_partner2_queue', 3046, FALSE, 100, '23000048', 'A1', 1900, '{DHL}'::zz_commons.parcel_service[], '{EQUIVALENT}'::zz_commons.parcel_service_type[]),
(3048, ARRAY[1]::smallint[],       3048::smallint, 'BestFashion4Kids',          'S + D Company GmbH',                      ARRAY['DE'], 'dblink_partner2_queue', 3048, FALSE, 100, '23000057', 'A1', 1900, '{DHL}'::zz_commons.parcel_service[], '{EQUIVALENT}'::zz_commons.parcel_service_type[]),
(3049, ARRAY[1]::smallint[],       3049::smallint, 'sassamode',                 'Maja Retail GmbH',                        ARRAY['DE'], 'dblink_partner1_queue', 3049, FALSE, 100, '23000050', 'A1', 1900, '{DHL}'::zz_commons.parcel_service[], '{EQUIVALENT}'::zz_commons.parcel_service_type[]),
(3050, ARRAY[1]::smallint[],       3050::smallint, 'Pro Fashion',               'Pro fashion gmbh',                        ARRAY['DE'], 'dblink_partner2_queue', 3050, FALSE, 100, '23000049', 'A1', 1900, '{DHL}'::zz_commons.parcel_service[], '{EQUIVALENT}'::zz_commons.parcel_service_type[]),
(3051, ARRAY[1]::smallint[],       3051::smallint, 'Amonda',                    'Amonda GmbH',                             ARRAY['DE'], 'dblink_partner1_queue', 3051, FALSE, 100, '23000055', 'A1', 1900, '{DHL}'::zz_commons.parcel_service[], '{EQUIVALENT}'::zz_commons.parcel_service_type[]),
(3052, ARRAY[1]::smallint[],       3052::smallint, 'Black-i',                   'Black-i GmbH & Co. KG',                   ARRAY['DE'], 'dblink_partner2_queue', 3052, FALSE, 100, '23000056', 'A1', 1900, '{DHL}'::zz_commons.parcel_service[], '{EQUIVALENT}'::zz_commons.parcel_service_type[]),
(3053, ARRAY[1]::smallint[],       3053::smallint, '1A Versand',                '1a Carl Friedrich Ern Versand',           ARRAY['DE'], 'dblink_partner1_queue', 3053, FALSE, 100, '23000057', 'A1', 1900, '{DHL}'::zz_commons.parcel_service[], '{EQUIVALENT}'::zz_commons.parcel_service_type[]),
(3054, ARRAY[1]::smallint[],       3054::smallint, '4egoLifestyle',             '4ego Lifestyle GmbH',                     ARRAY['DE'], 'dblink_partner2_queue', 3054, FALSE, 100, '23000058', 'A1', 1900, '{DHL}'::zz_commons.parcel_service[], '{EQUIVALENT}'::zz_commons.parcel_service_type[]),
(3055, ARRAY[1]::smallint[],       3055::smallint, 'Sympatico',                 'Sympatico Gründler & Richter GbR',        ARRAY['DE'], 'dblink_partner1_queue', 3055, TRUE,  100, '23000059', 'AC', 1900, '{DHL}'::zz_commons.parcel_service[], '{EQUIVALENT}'::zz_commons.parcel_service_type[]),
(3056, ARRAY[1]::smallint[],       3056::smallint, 'COLORADO Denim',            'Bay City Textilhandels GmbH',             ARRAY['DE'], 'dblink_partner2_queue', 3056, FALSE, 100, '23000060', 'A1', 1900, '{DHL}'::zz_commons.parcel_service[], '{EQUIVALENT}'::zz_commons.parcel_service_type[]),
(3057, ARRAY[1]::smallint[],       3057::smallint, 'Trigema',                   'Trigema Inh. W. Grupp e.K.',              ARRAY['DE'], 'dblink_partner1_queue', 3057, FALSE, 100, 'XXXXXXXX', 'A1', 1900, '{DHL}'::zz_commons.parcel_service[], '{EQUIVALENT}'::zz_commons.parcel_service_type[]),
(3058, ARRAY[1]::smallint[],       3058::smallint, 'Timestyles',                'Timestyles',                              ARRAY['DE'], 'dblink_partner2_queue', 3058, FALSE, 100, '23000064', 'A1', 1900, '{DHL}'::zz_commons.parcel_service[], '{EQUIVALENT}'::zz_commons.parcel_service_type[]),
(3059, ARRAY[1]::smallint[],       3059::smallint, 'RUNNERS POINT',             'Tredex GmbH',                             ARRAY['DE'], 'dblink_partner1_queue', 3059, FALSE, 100, '23000067', 'A1', 1900, '{DHL}'::zz_commons.parcel_service[], '{EQUIVALENT}'::zz_commons.parcel_service_type[]),
(3061, ARRAY[1]::smallint[],       3061::smallint, 'Golop',                     'Golop Handels-und Beteiligungs GmbH',     ARRAY['DE'], 'dblink_partner1_queue', 3061, FALSE, 100, '23000061', 'A1', 1900, '{DHL}'::zz_commons.parcel_service[], '{EQUIVALENT}'::zz_commons.parcel_service_type[]),
(3062, ARRAY[1]::smallint[],       3062::smallint, 'Indigo Bogner',             'Schwabe & Baer Entwicklungs GmbH',        ARRAY['DE'], 'dblink_partner2_queue', 3062, FALSE, 100, '23000068', 'A1', 1900, '{DHL}'::zz_commons.parcel_service[], '{EQUIVALENT}'::zz_commons.parcel_service_type[]),
(3063, ARRAY[1]::smallint[],       3063::smallint, 'Outfitter (Uhlsport)',      'OUTFITTER FIVE GmbH',                     ARRAY['DE'], 'dblink_partner1_queue', 3063, FALSE, 100, '23000003', 'A1', 1900, '{DHL}'::zz_commons.parcel_service[], '{EQUIVALENT}'::zz_commons.parcel_service_type[]),
(3064, ARRAY[1]::smallint[],       3064::smallint, 'Umbro',                     'OUTFITTER FIVE GmbH',                     ARRAY['DE'], 'dblink_partner2_queue', 3064, FALSE, 100, '23000003', 'A1', 1900, '{DHL}'::zz_commons.parcel_service[], '{EQUIVALENT}'::zz_commons.parcel_service_type[]),
(3065, ARRAY[1]::smallint[],       3065::smallint, 'vitality sports',           'vitality sports GmbH',                    ARRAY['DE'], 'dblink_partner1_queue', 3065, FALSE, 100, '23000070', 'A1', 1900, '{DHL}'::zz_commons.parcel_service[], '{EQUIVALENT}'::zz_commons.parcel_service_type[]),
(3066, ARRAY[1]::smallint[],       3066::smallint, 'DADA',                      'Ifemy''s Distributions GmbH',             ARRAY['DE'], 'dblink_partner2_queue', 3066, FALSE, 100, '23000071', 'A1', 1900, '{DHL}'::zz_commons.parcel_service[], '{EQUIVALENT}'::zz_commons.parcel_service_type[]),
(3067, ARRAY[1]::smallint[],       3067::smallint, 'mishoo',                    'Schuhkontor-Weimar GmbH',                 ARRAY['DE'], 'dblink_partner1_queue', 3067, FALSE, 100, '23000072', 'A1', 1900, '{DHL}'::zz_commons.parcel_service[], '{EQUIVALENT}'::zz_commons.parcel_service_type[]),
(3068, ARRAY[1]::smallint[],       3068::smallint, 'MI Showroom',               'MI Showroom GmbH',                        ARRAY['DE'], 'dblink_partner2_queue', 3068, FALSE, 100, '23000073', 'A1', 1900, '{DHL}'::zz_commons.parcel_service[], '{EQUIVALENT}'::zz_commons.parcel_service_type[]),
(3069, ARRAY[1]::smallint[],       3069::smallint, 'SCAROSSO',                  'Coremo GmbH',                             ARRAY['DE'], 'dblink_partner1_queue', 3069, FALSE, 100, '23000074', 'A1', 1900, '{DHL}'::zz_commons.parcel_service[], '{EQUIVALENT}'::zz_commons.parcel_service_type[]),
(3071, ARRAY[19]::smallint[],      3071::smallint, 'Outfitter',                 'OUTFITTER FIVE GmbH',                     ARRAY['AT'], 'dblink_partner1_queue', 3071, FALSE, 100, '23000003', 'A1', 1900, '{DHL}'::zz_commons.parcel_service[], '{ALTERNATIVE_INVISIBLE}'::zz_commons.parcel_service_type[]),
(3072, ARRAY[1]::smallint[],       3072::smallint, 'Playama',                   'Giggles Branding B.V.',                   ARRAY['DE'], 'dblink_partner2_queue', 3072, FALSE, 100, '23000075', 'AC', 0,    '{DHL}'::zz_commons.parcel_service[], '{EQUIVALENT}'::zz_commons.parcel_service_type[]),
(3073, ARRAY[1]::smallint[],       3073::smallint, 'Evita Shoes',               'Evitalys GmbH',                           ARRAY['DE'], 'dblink_partner1_queue', 3073, FALSE, 100, '23000084', 'A1', 1900, '{DHL}'::zz_commons.parcel_service[], '{EQUIVALENT}'::zz_commons.parcel_service_type[]),
(3074, ARRAY[1]::smallint[],       3074::smallint, 'PADDOCKS',                  'Ospig GmbH & Co. KG',                     ARRAY['DE'], 'dblink_partner2_queue', 3074, FALSE, 100, '23000087', 'A1', 1900, '{DHL}'::zz_commons.parcel_service[], '{EQUIVALENT}'::zz_commons.parcel_service_type[]),
(3075, ARRAY[1]::smallint[],       3075::smallint, 'Aikme',                     'aikme GmbH',                              ARRAY['DE'], 'dblink_partner1_queue', 3075, FALSE, 100, '23000088', 'A1', 1900, '{DHL}'::zz_commons.parcel_service[], '{EQUIVALENT}'::zz_commons.parcel_service_type[]),
(3076, ARRAY[1]::smallint[],       3076::smallint, 'KS-cycling',                'Schalow & Kroh GmbH',                     ARRAY['DE'], 'dblink_partner2_queue', 3076, FALSE, 100, '23000086', 'A1', 1900, '{DHL}'::zz_commons.parcel_service[], '{EQUIVALENT}'::zz_commons.parcel_service_type[]),
(3077, ARRAY[1]::smallint[],       3077::smallint, 'Jupiter',                   'Jupiter Bekleidung GmbH',                 ARRAY['DE'], 'dblink_partner1_queue', 3077, FALSE, 100, '23000083', 'A1', 1900, '{DHL}'::zz_commons.parcel_service[], '{EQUIVALENT}'::zz_commons.parcel_service_type[]),
(3078, ARRAY[1]::smallint[],       3078::smallint, 'Pionier Jeans und Casuals', 'Pionier Jeans & Casuals GmbH',            ARRAY['DE'], 'dblink_partner2_queue', 3078, FALSE, 100, '23000081', 'A1', 1900, '{DHL}'::zz_commons.parcel_service[], '{EQUIVALENT}'::zz_commons.parcel_service_type[]),
(3079, ARRAY[1]::smallint[],       3079::smallint, 'Pioneer Authentic Jeans',   'Pioneer Jeans-Bekleidung GmbH',           ARRAY['DE'], 'dblink_partner1_queue', 3079, FALSE, 100, '23000085', 'A1', 1900, '{DHL}'::zz_commons.parcel_service[], '{EQUIVALENT}'::zz_commons.parcel_service_type[]),
(3080, ARRAY[1]::smallint[],       3080::smallint, 'GIN TONIC',                 'Gin Tonic SPECIAL Mode GmbH',             ARRAY['DE'], 'dblink_partner2_queue', 3080, FALSE, 100, '23000082', 'A1', 1900, '{DHL}'::zz_commons.parcel_service[], '{EQUIVALENT}'::zz_commons.parcel_service_type[]),
(3081, ARRAY[1]::smallint[],       3081::smallint, 'Bayer Design',              'Fritz Bayer GmbH & Co. KG',               ARRAY['DE'], 'dblink_partner1_queue', 3081, FALSE, 100, '23000090', 'A1', 1900, '{DHL}'::zz_commons.parcel_service[], '{EQUIVALENT}'::zz_commons.parcel_service_type[]),
(3082, ARRAY[1]::smallint[],       3082::smallint, 'onQuality',                 'onQuality GmbH',                          ARRAY['DE'], 'dblink_partner2_queue', 3082, FALSE, 100, '23000080', 'A1', 1900, '{DHL}'::zz_commons.parcel_service[], '{EQUIVALENT}'::zz_commons.parcel_service_type[]),
(3083, ARRAY[1]::smallint[],       3083::smallint, 'Otto Kern',                 'Otto Kern GmbH',                          ARRAY['DE'], 'dblink_partner1_queue', 3083, FALSE, 100, '23000111', 'A1', 1900, '{DHL}'::zz_commons.parcel_service[], '{EQUIVALENT}'::zz_commons.parcel_service_type[]),
(3085, ARRAY[1]::smallint[],       3085::smallint, 'Baldessarini',              'Baldessarini GmbH',                       ARRAY['DE'], 'dblink_partner1_queue', 3085, FALSE, 100, '23000110', 'A1', 1900, '{DHL}'::zz_commons.parcel_service[], '{EQUIVALENT}'::zz_commons.parcel_service_type[]),
(3084, ARRAY[1]::smallint[],       3084::smallint, 'Pierre Cardin',             'Ahlers P. C. GmbH',                       ARRAY['DE'], 'dblink_partner2_queue', 3084, FALSE, 100, '23000099', 'A1', 1900, '{DHL}'::zz_commons.parcel_service[], '{EQUIVALENT}'::zz_commons.parcel_service_type[]),
(3086, ARRAY[1]::smallint[],       3086::smallint, 'Naturzeit',                 'Naturzeit GmbH & Co.KG',                  ARRAY['DE'], 'dblink_partner2_queue', 3086, FALSE, 100, '23000091', 'A1', 1900, '{DHL}'::zz_commons.parcel_service[], '{EQUIVALENT}'::zz_commons.parcel_service_type[]),
(3087, ARRAY[1]::smallint[],       3087::smallint, 'Outfitter',                 'OUTFITTER FIVE GmbH',                     ARRAY['DE'], 'dblink_partner1_queue', 3087, FALSE, 100, '23000003', 'A1', 1900, '{TNT}'::zz_commons.parcel_service[], '{EQUIVALENT}'::zz_commons.parcel_service_type[]),
(3089, ARRAY[1]::smallint[],       3089::smallint, 'KEY LARGO Shop',            'Emile Bausch Textilien GmbH',             ARRAY['DE'], 'dblink_partner1_queue', 3089, FALSE, 100, '23000094', 'A1', 1900, '{DHL}'::zz_commons.parcel_service[], '{EQUIVALENT}'::zz_commons.parcel_service_type[]),
(3090, ARRAY[1]::smallint[],       3090::smallint, 'Markenkoffer',              'Markenkoffer GmbH',                       ARRAY['DE'], 'dblink_partner2_queue', 3090, FALSE, 100, '23000095', 'A1', 1900, '{DHL}'::zz_commons.parcel_service[], '{EQUIVALENT}'::zz_commons.parcel_service_type[]),
(3092, ARRAY[1]::smallint[],       3092::smallint, 'Modestern',                 'Brandlots GmbH',                          ARRAY['DE'], 'dblink_partner2_queue', 3092, FALSE, 100, '23000092', 'A1', 1900, '{DHL}'::zz_commons.parcel_service[], '{EQUIVALENT}'::zz_commons.parcel_service_type[]),
(3093, ARRAY[1]::smallint[],       3093::smallint, 'atrendo',                   'piké lifestyle GmbH',                     ARRAY['DE'], 'dblink_partner1_queue', 3093, FALSE, 100, '23000098', 'A1', 1900, '{DHL}'::zz_commons.parcel_service[], '{EQUIVALENT}'::zz_commons.parcel_service_type[]),
(3094, ARRAY[1]::smallint[],       3094::smallint, 'Codello',                   'Codello Lifestyle Accessories GmbH',      ARRAY['DE'], 'dblink_partner2_queue', 3094, FALSE, 100, '23000097', 'A1', 1900, '{DHL}'::zz_commons.parcel_service[], '{EQUIVALENT}'::zz_commons.parcel_service_type[]),
(3095, ARRAY[1]::smallint[],       3095::smallint, 'Capellishop',               'Cheressi Concepts e.K',                   ARRAY['DE'], 'dblink_partner1_queue', 3095, FALSE, 100, '23000089', 'A1', 1900, '{DHL}'::zz_commons.parcel_service[], '{EQUIVALENT}'::zz_commons.parcel_service_type[]),
(3096, ARRAY[1]::smallint[],       3096::smallint, 'sOliver',                   's.Oliver Bernd Freier GmbH & Co. KG',     ARRAY['DE'], 'dblink_partner2_queue', 3096, FALSE, 100, '23000100', 'A1', 1900, '{DHL}'::zz_commons.parcel_service[], '{EQUIVALENT}'::zz_commons.parcel_service_type[]),
(3097, ARRAY[1]::smallint[],       3097::smallint, 'uhrcenter',                 'Esters GmbH',                             ARRAY['DE'], 'dblink_partner1_queue', 3097, FALSE, 100, '23000105', 'A1', 1900, '{DHL}'::zz_commons.parcel_service[], '{EQUIVALENT}'::zz_commons.parcel_service_type[]),
(3098, ARRAY[1]::smallint[],       3098::smallint, 'Naketano',                  'Naketano GmbH',                           ARRAY['DE'], 'dblink_partner2_queue', 3098, FALSE, 100, '23000106', 'A1', 1900, '{DHL}'::zz_commons.parcel_service[], '{EQUIVALENT}'::zz_commons.parcel_service_type[]),
(3099, ARRAY[1]::smallint[],       3099::smallint, 'Liameo',                    'Liameo GmbH',                             ARRAY['DE'], 'dblink_partner1_queue', 3099, FALSE, 100, '23000107', 'A1', 1900, '{DHL}'::zz_commons.parcel_service[], '{EQUIVALENT}'::zz_commons.parcel_service_type[]),
(3143, ARRAY[5]::smallint[],       3143::smallint, 'Noppies NL',                'Noppies NL',                              ARRAY['DE'], 'dblink_partner1_queue', 3143, TRUE,  100, '23000063', 'AC', 0,    '{DHL}'::zz_commons.parcel_service[], '{ALTERNATIVE_INVISIBLE}'::zz_commons.parcel_service_type[]),
(3100, ARRAY[1]::smallint[],       3100::smallint, 'Apart Fashion',             'Apart Fashion GmbH',                      ARRAY['DE'], 'dblink_partner2_queue', 3100, TRUE,  100, '23000108', 'A1', 1900, '{DHL}'::zz_commons.parcel_service[], '{EQUIVALENT}'::zz_commons.parcel_service_type[]),
(3101, ARRAY[1]::smallint[],       3101::smallint, 'cbecom',                    'cbecom Retail GmbH',                      ARRAY['DE'], 'dblink_partner1_queue', 3101, FALSE, 100, '23000109', 'A1', 1900, '{DHL}'::zz_commons.parcel_service[], '{EQUIVALENT}'::zz_commons.parcel_service_type[]),
(3102, ARRAY[1]::smallint[],       3102::smallint, 'Hallhuber',                 'Hallhuber GmbH',                          ARRAY['DE'], 'dblink_partner2_queue', 3102, FALSE, 100, '23000115', 'A1', 1900, '{DHL}'::zz_commons.parcel_service[], '{EQUIVALENT}'::zz_commons.parcel_service_type[]),
(3104, ARRAY[1]::smallint[],       3104::smallint, 'PureDay',                   'PM Product Marketing GmbH',               ARRAY['DE'], 'dblink_partner2_queue', 3104, FALSE, 100, '23000118', 'A1', 1900, '{DHL}'::zz_commons.parcel_service[], '{EQUIVALENT}'::zz_commons.parcel_service_type[]),
(3105, ARRAY[1]::smallint[],       3105::smallint, 'beach panties',             'SKINTOOLS Beauty GmbH',                   ARRAY['DE'], 'dblink_partner1_queue', 3105, FALSE, 100, '23000117', 'A1', 1900, '{DHL}'::zz_commons.parcel_service[], '{EQUIVALENT}'::zz_commons.parcel_service_type[]),
(3106, ARRAY[19]::smallint[],      3106::smallint, 'Sobeos',                    'sobeos GmbH',                             ARRAY['AT'], 'dblink_partner2_queue', 3106, FALSE, 100, '23000005', 'A1', 1900, '{DHL}'::zz_commons.parcel_service[], '{ALTERNATIVE_INVISIBLE}'::zz_commons.parcel_service_type[]),
(3107, ARRAY[19]::smallint[],      3107::smallint, 'Evita Shoes',               'Evitalys GmbH',                           ARRAY['AT'], 'dblink_partner1_queue', 3107, FALSE, 100, '23000084', 'A1', 1900, '{DHL}'::zz_commons.parcel_service[], '{ALTERNATIVE_INVISIBLE}'::zz_commons.parcel_service_type[]),
(3109, ARRAY[19]::smallint[],      3109::smallint, 'schuhplus',                 'SCHUHPLUS - The Footwear Company GmbH',   ARRAY['AT'], 'dblink_partner1_queue', 3109, FALSE, 100, '23000001', 'A1', 1900, '{DHL}'::zz_commons.parcel_service[], '{ALTERNATIVE_INVISIBLE}'::zz_commons.parcel_service_type[]),
(3110, ARRAY[19]::smallint[],      3110::smallint, 'Surf4shoes',                'surf4shoes GmbH',                         ARRAY['AT'], 'dblink_partner2_queue', 3110, FALSE, 100, '23000006', 'A1', 1900, '{DHL}'::zz_commons.parcel_service[], '{ALTERNATIVE_INVISIBLE}'::zz_commons.parcel_service_type[]),
(3112, ARRAY[19]::smallint[],      3112::smallint, 'Giesswein',                 'Giesswein Walzwaren AG',                  ARRAY['AT'], 'dblink_partner2_queue', 3112, FALSE, 100, '23000000', 'AC', 0,    '{DHL}'::zz_commons.parcel_service[], '{EQUIVALENT}'::zz_commons.parcel_service_type[]),
(3114, ARRAY[19]::smallint[],      3114::smallint, 'Koffer-Arena',              'tasko Products GmbH',                     ARRAY['AT'], 'dblink_partner2_queue', 3114, FALSE, 100, '23000020', 'A1', 1900, '{DHL}'::zz_commons.parcel_service[], '{ALTERNATIVE_INVISIBLE}'::zz_commons.parcel_service_type[]),
(3115, ARRAY[19]::smallint[],      3115::smallint, 'Fashionart',                'Fashionart Ltd. &amp; Co. KG',            ARRAY['AT'], 'dblink_partner1_queue', 3115, FALSE, 100, '23000035', 'A1', 1900, '{DHL}'::zz_commons.parcel_service[], '{ALTERNATIVE_INVISIBLE}'::zz_commons.parcel_service_type[]),
(3116, ARRAY[5]::smallint[],       3116::smallint, 'Sobeos',                    'sobeos GmbH',                             ARRAY['NL'], 'dblink_partner2_queue', 3116, FALSE, 100, '23000005', 'A1', 1900, '{DHL}'::zz_commons.parcel_service[], '{ALTERNATIVE_INVISIBLE}'::zz_commons.parcel_service_type[]),
(3117, ARRAY[5]::smallint[],       3117::smallint, 'schuhplus',                 'SCHUHPLUS - The Footwear Company GmbH',   ARRAY['NL'], 'dblink_partner1_queue', 3117, FALSE, 100, '23000001', 'A1', 1900, '{DHL}'::zz_commons.parcel_service[], '{ALTERNATIVE_INVISIBLE}'::zz_commons.parcel_service_type[]),
(3118, ARRAY[5]::smallint[],       3118::smallint, 'Surf4shoes',                'surf4shoes GmbH',                         ARRAY['NL'], 'dblink_partner2_queue', 3118, FALSE, 100, '23000006', 'A1', 1900, '{DHL}'::zz_commons.parcel_service[], '{ALTERNATIVE_INVISIBLE}'::zz_commons.parcel_service_type[]),
(3119, ARRAY[5]::smallint[],       3119::smallint, 'Center Court',              'Sportartikelvertrieb oHG',                ARRAY['NL'], 'dblink_partner1_queue', 3119, FALSE, 100, '23000033', 'A1', 1900, '{DHL}'::zz_commons.parcel_service[], '{ALTERNATIVE_INVISIBLE}'::zz_commons.parcel_service_type[]),
(3120, ARRAY[5]::smallint[],       3120::smallint, 'sc24',                      'SC24.com AG',                             ARRAY['NL'], 'dblink_partner2_queue', 3120, FALSE, 100, '23000010', 'A1', 1900, '{DHL}'::zz_commons.parcel_service[], '{ALTERNATIVE_INVISIBLE}'::zz_commons.parcel_service_type[]),
(3121, ARRAY[19]::smallint[],      3121::smallint, 'Center Court',              'Sportartikelvertrieb oHG',                ARRAY['AT'], 'dblink_partner1_queue', 3121, FALSE, 100, '23000033', 'A1', 1900, '{DHL}'::zz_commons.parcel_service[], '{ALTERNATIVE_INVISIBLE}'::zz_commons.parcel_service_type[]),
(3123, ARRAY[1]::smallint[],       3123::smallint, 'Bata',                      'BATA France Distribution SAS',            ARRAY['FR'], 'dblink_partner1_queue', 3123, FALSE, 100, '23000121', 'A3', 1960, '{LAP}'::zz_commons.parcel_service[], '{EQUIVALENT}'::zz_commons.parcel_service_type[]),
(3124, ARRAY[19]::smallint[],      3124::smallint, 'sc24',                      'SC24.com AG',                             ARRAY['AT'], 'dblink_partner2_queue', 3124, FALSE, 100, '23000010', 'A1', 1900, '{DHL}'::zz_commons.parcel_service[], '{ALTERNATIVE_INVISIBLE}'::zz_commons.parcel_service_type[]),
(3125, ARRAY[1]::smallint[],       3125::smallint, 'Fashionart',                'Fashionart Ltd. & Co. KG',                ARRAY['DE'], 'dblink_partner1_queue', 3125, FALSE, 100, '23000035', 'A1', 1900, '{DHL}'::zz_commons.parcel_service[], '{ALTERNATIVE_INVISIBLE}'::zz_commons.parcel_service_type[]),
(3127, ARRAY[19]::smallint[],      3127::smallint, 'cbecom',                    'cbecom Retail GmbH',                      ARRAY['AT'], 'dblink_partner1_queue', 3127, FALSE, 100, '23000109', 'A1', 1900, '{DHL}'::zz_commons.parcel_service[], '{ALTERNATIVE_INVISIBLE}'::zz_commons.parcel_service_type[]),
(3129, ARRAY[19]::smallint[],      3129::smallint, 'Coutie',                    'Coutie GmbH',                             ARRAY['AT'], 'dblink_partner1_queue', 3129, FALSE, 100, '23000002', 'A1', 1900, '{DHL}'::zz_commons.parcel_service[], '{ALTERNATIVE_INVISIBLE}'::zz_commons.parcel_service_type[]),
(3130, ARRAY[1]::smallint[],       3130::smallint, 'Brax',                      'Leineweber GmbH & Co. KG',                ARRAY['DE'], 'dblink_partner2_queue', 3130, FALSE, 100, '23000125', 'A1', 1900, '{DHL}'::zz_commons.parcel_service[], '{EQUIVALENT}'::zz_commons.parcel_service_type[]),
(3131, ARRAY[5]::smallint[],       3131::smallint, 'Coutie',                    'Coutie GmbH',                             ARRAY['NL'], 'dblink_partner1_queue', 3131, FALSE, 100, '23000002', 'A1', 1900, '{DHL}'::zz_commons.parcel_service[], '{ALTERNATIVE_INVISIBLE}'::zz_commons.parcel_service_type[]),
(3134, ARRAY[19]::smallint[],      3134::smallint, 'Hallhuber',                 'Hallhuber GmbH',                          ARRAY['AT'], 'dblink_partner2_queue', 3134, FALSE, 100, '23000115', 'A1', 1900, '{DHL}'::zz_commons.parcel_service[], '{ALTERNATIVE_INVISIBLE}'::zz_commons.parcel_service_type[])
;