CREATE TYPE constraint_violation as ENUM (
    'EAN_IN_USE',
    'UNKNOWN_COLOR_CODE',
    'UNKNOWN_MATERIAL_CODE',
    'UNKNOWN_SIZE_CHART_CODE',
    'UNKNOWN_SIZE_CODE',
    'UNKNOWN_COMMODITY_GROUP_CODE',
    'UNKNOWN_SEASON_CODE',
    'INVALID_SIZE_DIMENSION_GROUP',
    'DUPLICATED_COLORS_AND_MATERIAL_COMBINATION',
    'DUPLICATED_SIZES',
    'INCONSISTENT_DIMENSION_COUNT',
    'INCONSISTENT_SIZE_DATA'
);
