CREATE TYPE solr_article AS (
    simple_sku                  text,
    config_sku                  text,
    model_sku                   text,
    ean                         text,
    description                 text,
    is_zalando_article          boolean,
    is_partner_article          boolean,
    is_commission_article       boolean,
    color_code                  text,
    second_color_code           text,
    third_color_code            text,
    brand_code                  text,
    brand_code_original         text,
    season_code                 text,
    length_code                 text,
    size_code                   text,
    commodity_group_code        text,
    length_chart_code           text,
    size_chart_code             text,
    washing_code                text,
    color_descr_de              text,
    color_descr_en              text,
    brand_description           text,
    season_description          text,
    commodity_group_description text,
    washing_description         text,
    material_code               text,
    customs_code                text,
    initial_season_code         text,
    initial_purchase_price      text,
    initial_season_description  text,
    pattern                     text,
    color_description           text,
    solr_supplier_facets        solr_supplier_facet[]
);

