--CREATE SEQUENCE zzj_data.article_model_id_seq START WITH 1 INCREMENT BY 2;
--CREATE SEQUENCE zzj_data.article_config_id_seq START WITH 2 INCREMENT BY 2;
--CREATE SEQUENCE zzj_data.article_simple_id_seq START WITH 1 INCREMENT BY 1;