create type article_config as (
    version                       integer,
    config_sku                    text,
    first_season_code             text,
    season_code                   text,
    sub_season_type_code          option_value_type_code,
    main_color_code               text,
    second_color_code             text,
    third_color_code              text,
    main_material_code            text,
    reloaded_article              boolean,
    keystyle                      boolean,
    keystyle_delivery_date        timestamptz,
    disposition_locked            boolean,
    main_supplier_code            text,
    globally_rebateable           boolean,
    risk_article                  boolean,
    commission_article            boolean,
    key_value_item                boolean,
    pattern_type_code             option_value_type_code,
    sales_channels_release        sales_channels_release,
    simple_facets                 article_simple[]
);
