create type logistics_config as (
  version                       integer,
  config_sku                    text,
  country_of_origin             zz_commons.country_code,
  customs_code                  character(11),
  net_weight                    integer,
  gross_weight                  integer,
  net_volume                    integer,
  gross_volume                  integer,
  shipping_placement_type_code  option_value_type_code,
  cage_product                  boolean,
  fragile                       boolean,
  oversized_package             boolean,
  extra_heavy                   boolean,
  hazardous                     boolean,
  not_individually_packed       boolean,
  no_packaging                  boolean,
  unsafe_packaging              boolean,
  ce_certified                  boolean,
  article_set_size              integer,
  hanging_garment               boolean,
  functional_test_required      boolean,
  perishable                    boolean,
  comes_as_set                  boolean,
  simple_facets                 logistics_simple[]
);
