INSERT INTO zcat_commons.material
            (m_code,  m_type_id,    m_characteristic,               m_name_message_key,                                     m_created_by,  m_last_modified_by)
     VALUES ('001',   1,            'Lackleder',                    'material.PATENT_LEATHER.name',                         'bootstrap',   'bootstrap'),
            ('002',   1,            'Nubukleder',                   'material.NUBUCK_LEATHER.name',                         'bootstrap',   'bootstrap'),
            ('003',   1,            'Veloursleder',                 'material.SUEDE.name',                                  'bootstrap',   'bootstrap'),
            ('004',   1,            'Glattleder',                   'material.LEATHER.name',                                'bootstrap',   'bootstrap'),
            ('005',   1,            'Leder',                        'material.LEATHER_MIX.name',                            'bootstrap',   'bootstrap'),
            ('006',   1,            'Ledermix',                     'material.COMBINATION_OF_DIFFERENT_LEATHERS.name',      'bootstrap',   'bootstrap'),
            ('007',   1,            'Leder -Textil-Mix',            'material.LEATHER_TEXTILE.name',                        'bootstrap',   'bootstrap'),
            ('008',   1,            'Leder-Synthetik-Mix',          'material.COMBINATION_OF_LEATHER_AND_SYNTHETICS.name',  'bootstrap',   'bootstrap'),
            ('009',   1,            'Lederimitat/Kunstleder',       'material.IMITATION_LEATHER.name',                      'bootstrap',   'bootstrap'),
            ('010',   1,            'Lacklederimitat',              'material.IMITATION_PATENT_LEATHER.name',               'bootstrap',   'bootstrap'),
            ('011',   1,            'Nappaleder',                   'material.NAPPA_LEATHER.name',                          'bootstrap',   'bootstrap'),
            ('012',   1,            'Lammleder',                    'material.LAMBS_LEATHER.name',                          'bootstrap',   'bootstrap'),
            ('013',   1,            'Rindsleder',                   'material.COWHIDE.name',                                'bootstrap',   'bootstrap'),
            ('014',   1,            'Kalbsleder',                   'material.CALF''S_LEATHER.name',                        'bootstrap',   'bootstrap'),
            ('015',   1,            'Ziegenleder',                  'material.GOAT_LEATHER.name',                           'bootstrap',   'bootstrap'),
            ('016',   2,            'Textil',                       'material.TEXTILE.name',                                'bootstrap',   'bootstrap'),
            ('017',   2,            'Textil-Materialmix',           'material.COMBINATION_OF_DIFFERENT_FABRICS.name',       'bootstrap',   'bootstrap'),
            ('018',   2,            'Textil-Synthetik Mix',         'material.COMBINATION_OF_SYNTHETICS_AND_TEXTILE.name',  'bootstrap',   'bootstrap'),
            ('019',   2,            'Textil-Leder-Mix',             'material.COMBINATION_OF_LEATHER_AND_TEXTILES.name',    'bootstrap',   'bootstrap'),
            ('020',   2,            'Synthetik',                    'material.SYNTHETICS.name',                             'bootstrap',   'bootstrap'),
            ('021',   2,            'Baumwolle',                    'material.COTTON.name',                                 'bootstrap',   'bootstrap'),
            ('022',   2,            'Viskose',                      'material.VISCOSE.name',                                'bootstrap',   'bootstrap'),
            ('023',   2,            'Wolle',                        'material.WOOL.name',                                   'bootstrap',   'bootstrap'),
            ('024',   2,            'Polyester',                    'material.POLYESTER.name',                              'bootstrap',   'bootstrap'),
            ('025',   2,            'Modal',                        'material.MODAL.name',                                  'bootstrap',   'bootstrap'),
            ('026',   2,            'Seide',                        'material.SILK.name',                                   'bootstrap',   'bootstrap'),
            ('027',   2,            'Leinen (Flachs)',              'material.LINEN.name',                                  'bootstrap',   'bootstrap'),
            ('028',   2,            'Mohair',                       'material.MOHAIR.name',                                 'bootstrap',   'bootstrap'),
            ('029',   2,            'Kaschmir',                     'material.CASHMERE.name',                               'bootstrap',   'bootstrap'),
            ('030',   2,            'Lyocell',                      'material.LYOCELL.name',                                'bootstrap',   'bootstrap'),
            ('031',   2,            'Cupro',                        'material.CUPRO.name',                                  'bootstrap',   'bootstrap'),
            ('032',   2,            'Acetat',                       'material.ACETATE.name',                                'bootstrap',   'bootstrap'),
            ('033',   2,            'Kapok',                        'material.KAPOK.name',                                  'bootstrap',   'bootstrap'),
            ('034',   2,            'Hanf',                         'material.HEMP.name',                                   'bootstrap',   'bootstrap'),
            ('035',   2,            'Jute',                         'material.JUTE.name',                                   'bootstrap',   'bootstrap'),
            ('036',   2,            'Ramie',                        'material.RAMIE.name',                                  'bootstrap',   'bootstrap'),
            ('037',   2,            'Sisal',                        'material.SISAL.name',                                  'bootstrap',   'bootstrap'),
            ('038',   2,            'Alpaka',                       'material.ALPACA.name',                                 'bootstrap',   'bootstrap'),
            ('039',   2,            'Lama',                         'material.LLAMA.name',                                  'bootstrap',   'bootstrap'),
            ('040',   2,            'Vikunja',                      'material.VICUGNA.name',                                'bootstrap',   'bootstrap'),
            ('041',   2,            'Guanako',                      'material.GUANACO.name',                                'bootstrap',   'bootstrap'),
            ('042',   2,            'Kamel',                        'material.CAMEL.name',                                  'bootstrap',   'bootstrap'),
            ('043',   2,            'Kanin',                        'material.RABBIT.name',                                 'bootstrap',   'bootstrap'),
            ('044',   2,            'Angora',                       'material.ANGORA.name',                                 'bootstrap',   'bootstrap'),
            ('045',   2,            'Kaschgora',                    'material.CASHGORA.name',                               'bootstrap',   'bootstrap'),
            ('046',   2,            'Yak',                          'material.YAK.name',                                    'bootstrap',   'bootstrap'),
            ('047',   2,            'Rinderhaar',                   'material.COW_HAIR.name',                               'bootstrap',   'bootstrap'),
            ('048',   2,            'Rosshaar',                     'material.HORSEHAIR.name',                              'bootstrap',   'bootstrap'),
            ('049',   2,            'Ziegenhaar',                   'material.GOAT_HAIR.name',                              'bootstrap',   'bootstrap'),
            ('050',   2,            'Elastan',                      'material.ELASTANE.name',                               'bootstrap',   'bootstrap'),
            ('051',   2,            'Polyacryl',                    'material.POLYACRYLIC.name',                            'bootstrap',   'bootstrap'),
            ('052',   2,            'Polyamid',                     'material.POLYAMIDE.name',                              'bootstrap',   'bootstrap'),
            ('053',   2,            'Polyethylen',                  'material.POLYETHYLENE.name',                           'bootstrap',   'bootstrap'),
            ('054',   2,            'Microfaser',                   'material.MICROFIBRE.name',                             'bootstrap',   'bootstrap'),
            ('055',   2,            'Merinowolle',                  'material.MERINO_WOOL.name',                            'bootstrap',   'bootstrap'),
            ('056',   2,            'Polyvinylchlorid',             'material.POLYVINYL_CHLORIDE.name',                     'bootstrap',   'bootstrap'),
            ('057',   2,            'Polyurethan',                  'material.POLYURETHANE.name',                           'bootstrap',   'bootstrap'),
            ('058',   2,            'Nylon',                        'material.NYLON.name',                                  'bootstrap',   'bootstrap'),
            ('059',   2,            'Tencel',                       'material.TENCEL.name',                                 'bootstrap',   'bootstrap'),
            ('060',   2,            'Lurex',                        'material.LUREX.name',                                  'bootstrap',   'bootstrap'),
            ('061',   2,            'Sonstiges/Others',             'material.OTHER.name',                                  'bootstrap',   'bootstrap'),
            ('062',   3,            'Fell',                         'material.FUR.name',                                    'bootstrap',   'bootstrap'),
            ('063',   3,            'Lammfell',                     'material.LAMBSKIN.name',                               'bootstrap',   'bootstrap'),
            ('064',   3,            'Kunstfell / Webpelz',          'material.FAUX_FUR.name',                               'bootstrap',   'bootstrap'),
            ('065',   3,            'Naturmaterial (Stroh + Bast)', 'material.NATURAL_MATERIALS.name',                      'bootstrap',   'bootstrap'),
            ('066',   3,            'Gummi',                        'material.RUBBER.name',                                 'bootstrap',   'bootstrap'),
            ('067',   3,            'Naturkautschuk',               'material.NATURAL_RUBBER.name',                         'bootstrap',   'bootstrap'),
            ('068',   3,            'Glas',                         'material.GLASS.name',                                  'bootstrap',   'bootstrap'),
            ('069',   3,            'Metall',                       'material.METAL.name',                                  'bootstrap',   'bootstrap'),
            ('070',   3,            'Silber',                       'material.SILVER.name',                                 'bootstrap',   'bootstrap'),
            ('071',   3,            'Gold',                         'material.GOLD.name',                                   'bootstrap',   'bootstrap'),
            ('072',   3,            'Silber 925',                   'material.925_SILVER.name',                             'bootstrap',   'bootstrap'),
            ('073',   3,            'Titan',                        'material.TITANIUM.name',                               'bootstrap',   'bootstrap'),
            ('074',   3,            'Carbon',                       'material.CARBON.name',                                 'bootstrap',   'bootstrap'),
            ('075',   3,            'Stroh',                        'material.STRAW.name',                                  'bootstrap',   'bootstrap'),
            ('076',   3,            'Gel',                          'material.GEL.name',                                    'bootstrap',   'bootstrap'),
            ('077',   3,            'Holz',                         'material.WOOD.name',                                   'bootstrap',   'bootstrap'),
            ('078',   3,            'Buchenholz',                   'material.BEECH_WOOD.name',                             'bootstrap',   'bootstrap'),
            ('079',   3,            'Zedernholz',                   'material.CEDAR_WOOD.name',                             'bootstrap',   'bootstrap'),
            ('080',   3,            'Schaumstoff',                  'material.FOAM.name',                                   'bootstrap',   'bootstrap'),
            ('081',   3,            'Stahl',                        'material.STEEL.name',                                  'bootstrap',   'bootstrap'),
            ('082',   3,            'Aluminium',                    'material.ALUMINIUM.name',                              'bootstrap',   'bootstrap'),
            ('083',   3,            'Filz',                         'material.FELT.name',                                   'bootstrap',   'bootstrap'),
            ('084',   3,            'Kupfer',                       'material.COPPER.name',                                 'bootstrap',   'bootstrap'),
            ('085',   3,            'Kunststoff',                   'material.PLASTIC.name',                                'bootstrap',   'bootstrap'),
            ('086',   3,            'Versilberter Edelstahl',       'material.SILVER_PLATED_STAINLESS_STEEL.name',          'bootstrap',   'bootstrap'),
            ('087',   3,            'Vergoldetes metall',           'material.GOLD_PLATED_METAL.name',                      'bootstrap',   'bootstrap'),
            ('088',   3,            'Versilbertes Kupfer',          'material.SILVER_PLATED_COPPER.name',                   'bootstrap',   'bootstrap'),
            ('089',   3,            'Vergoldetes Kupfer',           'material.GOLD_PLATED_COPPER.name',                     'bootstrap',   'bootstrap'),
            ('090',   3,            'Vergoldetes Sterlingsilber',   'material.GOLD_PLATED_STERLING_SILVER.name',            'bootstrap',   'bootstrap'),
            ('091',   3,            'Vergoldeter Edelstahl',        'material.GOLD_PLATED_STAINLESS_STEEL.name',            'bootstrap',   'bootstrap'),
            ('092',   3,            'Edelstahl',                    'material.STAINLESS_STEEL.name',                        'bootstrap',   'bootstrap'),
            ('093',   3,            'Silikon',                      'material.SILICON.name',                                'bootstrap',   'bootstrap'),
            ('094',   3,            'Rosegold',                     'material.ROSE_GOLD.name',                              'bootstrap',   'bootstrap'),
            ('095',   3,            'Kunstharz',                    'material.SYNTHETIC_RESIN.name',                        'bootstrap',   'bootstrap'),
            ('096',   3,            'Weissgold',                    'material.WHITE_GOLD.name',                             'bootstrap',   'bootstrap'),
            ('097',   3,            'Keramik',                      'material.CERAMIC.name',                                'bootstrap',   'bootstrap'),
            ('098',   3,            'Acrylglas',                    'material.ACRYLIC_GLASS.name',                          'bootstrap',   'bootstrap'),
            ('099',   3,            'Mineralglas',                  'material.MINERAL_GLASS.name',                          'bootstrap',   'bootstrap'),
            ('100',   3,            'Saphirglas',                   'material.SAPPHIRE_GLASS.name',                         'bootstrap',   'bootstrap');
